/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login as admin */
        post: operations["loginAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh admin access and refresh tokens */
        post: operations["refreshAdminSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke one admin refresh session */
        post: operations["logoutAdminSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/catalog/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List categories by activity flag */
        get: operations["getAdminCategories"];
        put?: never;
        /** Create or update category */
        post: operations["upsertCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/catalog/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List products by activity flag */
        get: operations["getAdminProducts"];
        put?: never;
        /** Create or update product */
        post: operations["upsertProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/catalog/modifier-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List modifier groups */
        get: operations["getAdminModifierGroups"];
        put?: never;
        /** Create or update modifier group */
        post: operations["upsertModifierGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/products/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one product by id (admin) */
        get: operations["getAdminProductById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/catalog-import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import catalog entities from CSV
         * @description Accepts CSV file as `multipart/form-data` and processes import in one of the supported modes.
         *     Alias route is also available at `/api/admin/catalog-import`.
         */
        post: operations["importCatalog"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/catalog-import/examples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available CSV import examples
         * @description Alias route is also available at `/api/admin/catalog-import/examples`.
         */
        get: operations["listCatalogImportExamples"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/catalog-import/examples/{importType}/{importMode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download CSV import example by type and mode
         * @description Alias route is also available at `/api/admin/catalog-import/examples/{importType}/{importMode}`.
         */
        get: operations["downloadCatalogImportExample"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/catalog-import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import catalog CSV file
         * @deprecated
         * @description Legacy alias for `/api/v1/admin/catalog-import`.
         */
        post: operations["importCatalogLegacy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/catalog-import/examples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available example CSV files for catalog import
         * @deprecated
         * @description Legacy alias for `/api/v1/admin/catalog-import/examples`.
         */
        get: operations["listCatalogImportExamplesLegacy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/catalog-import/examples/{importType}/{importMode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download example CSV file for catalog import
         * @deprecated
         * @description Legacy alias for `/api/v1/admin/catalog-import/examples/{importType}/{importMode}`.
         */
        get: operations["downloadCatalogImportExampleLegacy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/delivery/methods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List delivery method settings */
        get: operations["getAdminDeliveryMethodSettings"];
        put?: never;
        /** Create or update delivery method setting */
        post: operations["upsertAdminDeliveryMethodSetting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/delivery/zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List delivery zones */
        get: operations["getAdminDeliveryZones"];
        put?: never;
        /** Create or update delivery zone */
        post: operations["upsertAdminDeliveryZone"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/delivery/zones/{zoneId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get delivery zone by id */
        get: operations["getAdminDeliveryZone"];
        /** Update delivery zone */
        put: operations["updateAdminDeliveryZone"];
        post?: never;
        /** Delete delivery zone */
        delete: operations["deleteAdminDeliveryZone"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/delivery/tariffs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List delivery tariffs */
        get: operations["getAdminDeliveryTariffs"];
        put?: never;
        /** Create or update delivery tariff */
        post: operations["upsertAdminDeliveryTariff"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/delivery/tariffs/{tariffId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete delivery tariff */
        delete: operations["deleteAdminDeliveryTariff"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/delivery/pickup-points": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List internal pickup points */
        get: operations["getAdminPickupPoints"];
        put?: never;
        /** Create or update internal pickup point */
        post: operations["upsertAdminPickupPoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/delivery/pickup-points/address-detect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Detect pickup point address by coordinates */
        post: operations["detectAdminPickupPointAddress"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/delivery/pickup-points/{pickupPointId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete internal pickup point */
        delete: operations["deleteAdminPickupPoint"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/delivery/payment-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List checkout payment rules by delivery method */
        get: operations["getAdminCheckoutPaymentRules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/delivery/payment-rules/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Replace checkout payment rules for static delivery methods
         * @description Replaces configured payment methods for delivery methods with static checkout rules.
         *     Dynamic methods such as `YANDEX_PICKUP_POINT` are returned in responses but cannot be changed here.
         */
        post: operations["replaceAdminCheckoutPaymentRules"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/order-statuses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List configurable order statuses */
        get: operations["getOrderStatuses"];
        put?: never;
        /** Create order status definition */
        post: operations["createOrderStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/order-statuses/{statusId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one order status definition */
        get: operations["getOrderStatus"];
        /** Update order status definition */
        put: operations["updateOrderStatusDefinition"];
        post?: never;
        /** Deactivate order status definition */
        delete: operations["deactivateOrderStatus"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/order-status-transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List order status transitions */
        get: operations["getOrderStatusTransitions"];
        put?: never;
        /** Create order status transition */
        post: operations["createOrderStatusTransition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/order-status-transitions/{transitionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete order status transition */
        delete: operations["deleteOrderStatusTransition"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List admin queue orders
         * @description Returns orders in active non-final workflow states, sorted by `createdAt` descending.
         */
        get: operations["getAdminOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/orders/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find order by number
         * @description Returns one order by exact `orderNumber` match.
         */
        get: operations["getAdminOrderByNumber"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/orders/{orderId}/available-status-transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available transitions for order */
        get: operations["getAvailableOrderStatusTransitions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/orders/{orderId}/status-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List order status history */
        get: operations["getOrderStatusHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/orders/{orderId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change order status */
        post: operations["changeOrderStatus"];
        delete?: never;
        options?: never;
        head?: never;
        /** Update order status */
        patch: operations["updateOrderStatus"];
        trace?: never;
    };
    "/api/v1/admin/telegram/test-message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Telegram test message to configured recipients */
        post: operations["sendTelegramTestMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/media/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create direct upload session for media image
         * @description Returns pre-signed upload URL and required headers.
         *     Actual binary upload happens directly to object storage URL, not via this backend.
         */
        post: operations["createMediaUploadSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/media/uploads/{uploadId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete upload session and bind image to target entity */
        post: operations["completeMediaUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiError: {
            /** @enum {string} */
            code: "VALIDATION_ERROR" | "UNAUTHORIZED" | "FORBIDDEN" | "NOT_FOUND" | "INTERNAL_ERROR";
            message: string;
            /** @description Request trace id (`X-Trace-Id`) when available. */
            traceId?: string | null;
            details?: {
                [key: string]: unknown;
            } | null;
        };
        AdminLoginRequest: {
            login: string;
            password: string;
            deviceId?: string | null;
        };
        AdminRefreshTokenRequest: {
            refreshToken: string;
            deviceId?: string | null;
        };
        AdminLogoutRequest: {
            refreshToken?: string | null;
        };
        AdminAuthTokensResponse: {
            accessToken: string;
            /** Format: date-time */
            accessTokenExpiresAt: string;
            refreshToken: string;
            /** Format: date-time */
            refreshTokenExpiresAt: string;
            /** Format: uuid */
            adminId: string;
        };
        DeliveryMethodSettingResponse: {
            method: components["schemas"]["DeliveryMethodType"];
            name: string;
            requiresAddress: boolean;
            requiresPickupPoint: boolean;
            isEnabled: boolean;
            /** Format: int32 */
            sortOrder: number;
        };
        UpsertDeliveryMethodSettingRequest: {
            method: components["schemas"]["DeliveryMethodType"];
            isEnabled: boolean;
            /** Format: int32 */
            sortOrder: number;
        };
        DeliveryZoneResponse: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            type: components["schemas"]["DeliveryZoneType"];
            city?: string | null;
            normalizedCity?: string | null;
            postalCode?: string | null;
            geometry?: components["schemas"]["DeliveryZoneGeometry"] | null;
            /**
             * Format: int32
             * @description Higher value means higher priority when polygon delivery zones overlap.
             */
            priority: number;
            isActive: boolean;
        };
        UpsertDeliveryZoneRequest: {
            /** Format: uuid */
            id?: string | null;
            code: string;
            name: string;
            type: components["schemas"]["DeliveryZoneType"];
            city?: string | null;
            postalCode?: string | null;
            geometry?: components["schemas"]["DeliveryZoneGeometry"] | null;
            /**
             * Format: int32
             * @description Higher value means higher priority when polygon delivery zones overlap.
             */
            priority?: number;
            isActive: boolean;
        };
        DeliveryZoneGeometry: {
            type: components["schemas"]["GeoJsonGeometryType"];
            /** @description GeoJSON-like coordinates. Request accepts Polygon or MultiPolygon nesting, response returns MultiPolygon nesting. */
            coordinates: unknown[];
        };
        DeliveryTariffResponse: {
            /** Format: uuid */
            id: string;
            method: components["schemas"]["DeliveryMethodType"];
            /** Format: uuid */
            zoneId?: string | null;
            zoneCode?: string | null;
            zoneName?: string | null;
            isAvailable: boolean;
            /** Format: int64 */
            fixedPriceMinor: number;
            /** Format: int64 */
            freeFromAmountMinor?: number | null;
            currency: string;
            /** Format: int32 */
            estimatedDays?: number | null;
            /** Format: int32 */
            deliveryMinutes?: number | null;
        };
        UpsertDeliveryTariffRequest: {
            /** Format: uuid */
            id?: string | null;
            method: components["schemas"]["DeliveryMethodType"];
            /** Format: uuid */
            zoneId?: string | null;
            isAvailable: boolean;
            /** Format: int64 */
            fixedPriceMinor: number;
            /** Format: int64 */
            freeFromAmountMinor?: number | null;
            currency: string;
            /** Format: int32 */
            estimatedDays?: number | null;
            /** Format: int32 */
            deliveryMinutes?: number | null;
        };
        AdminPickupPointResponse: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            address: components["schemas"]["DeliveryAddressResponse"];
            isActive: boolean;
        };
        UpsertPickupPointRequest: {
            /** Format: uuid */
            id?: string | null;
            code: string;
            name: string;
            address: components["schemas"]["DeliveryAddressRequest"];
            isActive: boolean;
        };
        DetectPickupPointAddressRequest: {
            /** Format: double */
            latitude: number;
            /** Format: double */
            longitude: number;
        };
        DetectPickupPointAddressResponse: {
            address: components["schemas"]["DeliveryAddressResponse"] | null;
        };
        CheckoutPaymentRuleResponse: {
            deliveryMethod: components["schemas"]["DeliveryMethodType"];
            deliveryMethodName: string;
            paymentMethods: components["schemas"]["PaymentMethodCode"][];
            isDynamic: boolean;
        };
        ReplaceCheckoutPaymentRulesRequest: {
            rules: components["schemas"]["UpsertCheckoutPaymentRuleRequest"][];
        };
        UpsertCheckoutPaymentRuleRequest: {
            deliveryMethod: components["schemas"]["DeliveryMethodType"];
            paymentMethods?: components["schemas"]["PaymentMethodCode"][];
        };
        CategoryResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            imageUrls: string[];
            isActive: boolean;
        };
        ProductResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            categoryId: string;
            title: string;
            slug: string;
            description?: string | null;
            brand?: string | null;
            /** Format: int64 */
            priceMinor: number;
            /** Format: int64 */
            oldPriceMinor?: number | null;
            sku?: string | null;
            imageUrls: string[];
            unit: components["schemas"]["ProductUnit"];
            /** Format: int32 */
            countStep: number;
            isActive: boolean;
            isConfigured: boolean;
        };
        AdminProductDetailsResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            categoryId: string;
            title: string;
            slug: string;
            description?: string | null;
            /** Format: int64 */
            priceMinor: number;
            /** Format: int64 */
            oldPriceMinor?: number | null;
            sku?: string | null;
            imageIds: string[];
            imageUrls: string[];
            unit: components["schemas"]["ProductUnit"];
            /** Format: int32 */
            countStep: number;
            isActive: boolean;
            isConfigured: boolean;
            optionGroups: components["schemas"]["ProductOptionGroupResponse"][];
            modifierGroups: components["schemas"]["ProductModifierGroupResponse"][];
            /** Format: uuid */
            defaultVariantId?: string | null;
            variants: components["schemas"]["AdminProductVariantResponse"][];
        };
        ProductOptionGroupResponse: {
            /** Format: uuid */
            id: string;
            code: string;
            title: string;
            /** Format: int32 */
            sortOrder: number;
            values: components["schemas"]["ProductOptionValueResponse"][];
        };
        ProductModifierGroupResponse: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            /** Format: int32 */
            minSelected: number;
            /** Format: int32 */
            maxSelected: number;
            isRequired: boolean;
            isActive: boolean;
            /** Format: int32 */
            sortOrder: number;
            options: components["schemas"]["ProductModifierOptionResponse"][];
        };
        ProductModifierOptionResponse: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            description?: string | null;
            priceType: components["schemas"]["ModifierPriceType"];
            /** Format: int64 */
            price: number;
            applicationScope: components["schemas"]["ModifierApplicationScope"];
            isDefault: boolean;
            isActive: boolean;
            /** Format: int32 */
            sortOrder: number;
        };
        ModifierGroupResponse: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            /** Format: int32 */
            minSelected: number;
            /** Format: int32 */
            maxSelected: number;
            isRequired: boolean;
            isActive: boolean;
            /** Format: int32 */
            sortOrder: number;
            options: components["schemas"]["ModifierOptionResponse"][];
        };
        ModifierOptionResponse: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            description?: string | null;
            priceType: components["schemas"]["ModifierPriceType"];
            /** Format: int64 */
            price: number;
            applicationScope: components["schemas"]["ModifierApplicationScope"];
            isDefault: boolean;
            isActive: boolean;
            /** Format: int32 */
            sortOrder: number;
        };
        ProductOptionValueResponse: {
            /** Format: uuid */
            id: string;
            code: string;
            title: string;
            /** Format: int32 */
            sortOrder: number;
        };
        AdminProductVariantResponse: {
            /** Format: uuid */
            id: string;
            externalId?: string | null;
            sku: string;
            title?: string | null;
            /** Format: int64 */
            priceMinor?: number | null;
            /** Format: int64 */
            oldPriceMinor?: number | null;
            imageIds: string[];
            imageUrls: string[];
            /** Format: int32 */
            sortOrder: number;
            isActive: boolean;
            optionValueIds: string[];
        };
        UpsertCategoryRequest: {
            /** Format: uuid */
            id?: string | null;
            name: string;
            slug?: string | null;
            imageIds?: string[];
            /** @default true */
            isActive: boolean;
        };
        UpsertProductRequest: {
            /** Format: uuid */
            id?: string | null;
            /** Format: uuid */
            categoryId: string;
            title: string;
            slug?: string | null;
            description?: string | null;
            /** Format: int64 */
            priceMinor: number;
            /** Format: int64 */
            oldPriceMinor?: number | null;
            sku?: string | null;
            imageIds?: string[];
            unit: components["schemas"]["ProductUnit"];
            /** Format: int32 */
            countStep: number;
            /** @default true */
            isActive: boolean;
            optionGroups?: components["schemas"]["UpsertProductOptionGroupRequest"][];
            modifierGroups?: components["schemas"]["UpsertProductModifierGroupLinkRequest"][];
            variants?: components["schemas"]["UpsertProductVariantRequest"][];
        };
        UpsertModifierGroupRequest: {
            /** Format: uuid */
            id?: string | null;
            code: string;
            name: string;
            /** Format: int32 */
            minSelected: number;
            /** Format: int32 */
            maxSelected: number;
            /** @default false */
            isRequired: boolean;
            /** @default true */
            isActive: boolean;
            /**
             * Format: int32
             * @default 0
             */
            sortOrder: number;
            options?: components["schemas"]["UpsertModifierOptionRequest"][];
        };
        UpsertModifierOptionRequest: {
            code: string;
            name: string;
            description?: string | null;
            priceType: components["schemas"]["ModifierPriceType"];
            /** Format: int64 */
            price?: number;
            applicationScope: components["schemas"]["ModifierApplicationScope"];
            /** @default false */
            isDefault: boolean;
            /** @default true */
            isActive: boolean;
            /**
             * Format: int32
             * @default 0
             */
            sortOrder: number;
        };
        UpsertProductModifierGroupLinkRequest: {
            /** Format: uuid */
            modifierGroupId: string;
            /**
             * Format: int32
             * @default 0
             */
            sortOrder: number;
            /** @default true */
            isActive: boolean;
        };
        UpsertProductOptionGroupRequest: {
            code: string;
            title: string;
            /**
             * Format: int32
             * @default 0
             */
            sortOrder: number;
            values?: components["schemas"]["UpsertProductOptionValueRequest"][];
        };
        UpsertProductOptionValueRequest: {
            code: string;
            title: string;
            /**
             * Format: int32
             * @default 0
             */
            sortOrder: number;
        };
        UpsertProductVariantRequest: {
            externalId?: string | null;
            sku: string;
            title?: string | null;
            /** Format: int64 */
            priceMinor?: number | null;
            /** Format: int64 */
            oldPriceMinor?: number | null;
            imageIds?: string[];
            /**
             * Format: int32
             * @default 0
             */
            sortOrder: number;
            /** @default true */
            isActive: boolean;
            options?: components["schemas"]["UpsertProductVariantOptionRequest"][];
        };
        UpsertProductVariantOptionRequest: {
            optionGroupCode: string;
            optionValueCode: string;
        };
        CatalogImportMultipartRequest: {
            /**
             * Format: binary
             * @description Header-based CSV file encoded in UTF-8 with comma delimiter.
             */
            file: string;
            importType: components["schemas"]["CatalogImportType"];
            importMode: components["schemas"]["CatalogImportMode"];
        };
        CatalogImportResponse: {
            importType: components["schemas"]["CatalogImportType"];
            importMode: components["schemas"]["CatalogImportMode"];
            /** Format: int32 */
            totalRows: number;
            /** Format: int32 */
            successCount: number;
            /** Format: int32 */
            createdCount: number;
            /** Format: int32 */
            updatedCount: number;
            /** Format: int32 */
            skippedCount: number;
            /** Format: int32 */
            errorCount: number;
            rowErrors: components["schemas"]["CatalogImportRowErrorResponse"][];
        };
        CatalogImportRowErrorResponse: {
            /** Format: int32 */
            rowNumber: number;
            rowKey?: string | null;
            errorCode: components["schemas"]["CatalogImportErrorCode"];
            message: string;
        };
        CatalogImportExampleResponse: {
            importType: components["schemas"]["CatalogImportType"];
            importMode: components["schemas"]["CatalogImportMode"];
            fileName: string;
            downloadUrl: string;
        };
        UpdateOrderStatusRequest: {
            /** Format: uuid */
            statusId?: string | null;
            statusCode?: string | null;
            /** @description Legacy alias for `statusCode`. */
            status?: string | null;
            comment?: string | null;
        };
        OrderStatusSummaryResponse: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            stateType: components["schemas"]["OrderStateType"];
            color?: string | null;
            icon?: string | null;
            isFinal: boolean;
            isCancellable: boolean;
            visibleToCustomer: boolean;
        };
        OrderStatusResponse: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            description?: string | null;
            stateType: components["schemas"]["OrderStateType"];
            color?: string | null;
            icon?: string | null;
            isInitial: boolean;
            isFinal: boolean;
            isCancellable: boolean;
            isActive: boolean;
            visibleToCustomer: boolean;
            notifyCustomer: boolean;
            notifyStaff: boolean;
            /** Format: int32 */
            sortOrder: number;
        };
        UpsertOrderStatusRequest: {
            /** Format: uuid */
            id?: string | null;
            code: string;
            name: string;
            description?: string | null;
            stateType: components["schemas"]["OrderStateType"];
            color?: string | null;
            icon?: string | null;
            /** @default false */
            isInitial: boolean;
            /** @default false */
            isFinal: boolean;
            /** @default false */
            isCancellable: boolean;
            /** @default true */
            isActive: boolean;
            /** @default true */
            visibleToCustomer: boolean;
            /** @default false */
            notifyCustomer: boolean;
            /** @default true */
            notifyStaff: boolean;
            /** Format: int32 */
            sortOrder?: number;
        };
        OrderStatusTransitionResponse: {
            /** Format: uuid */
            id: string;
            fromStatus: components["schemas"]["OrderStatusSummaryResponse"];
            toStatus: components["schemas"]["OrderStatusSummaryResponse"];
            requiredRole?: components["schemas"]["UserRole"];
            isAutomatic: boolean;
            guardCode?: string | null;
            isActive: boolean;
        };
        CreateOrderStatusTransitionRequest: {
            /** Format: uuid */
            fromStatusId: string;
            /** Format: uuid */
            toStatusId: string;
            requiredRole?: components["schemas"]["UserRole"];
            /** @default false */
            isAutomatic: boolean;
            guardCode?: string | null;
            /** @default true */
            isActive: boolean;
        };
        OrderStatusHistoryResponse: {
            /** Format: uuid */
            id: string;
            previousStatus?: components["schemas"]["OrderStatusSummaryResponse"] | null;
            currentStatus: components["schemas"]["OrderStatusSummaryResponse"];
            changeSourceType: components["schemas"]["OrderStatusChangeSourceType"];
            /** Format: uuid */
            changedByUserId?: string | null;
            comment?: string | null;
            /** Format: date-time */
            changedAt: string;
        };
        OrderResponse: {
            /** Format: uuid */
            id: string;
            orderNumber: string;
            customerType: components["schemas"]["OrderCustomerType"];
            /** Format: uuid */
            userId?: string | null;
            guestInstallId?: string | null;
            customerName?: string | null;
            customerPhone?: string | null;
            customerEmail?: string | null;
            status: string;
            statusName: string;
            stateType: components["schemas"]["OrderStateType"];
            currentStatus: components["schemas"]["OrderStatusSummaryResponse"];
            payment?: components["schemas"]["OrderPaymentResponse"] | null;
            deliveryMethod: components["schemas"]["DeliveryMethodType"];
            delivery: components["schemas"]["OrderDeliveryResponse"];
            comment?: string | null;
            items: components["schemas"]["OrderItemResponse"][];
            /** Format: int64 */
            subtotalMinor: number;
            /** Format: int64 */
            deliveryFeeMinor: number;
            /** Format: int64 */
            totalMinor: number;
            /** Format: date-time */
            statusChangedAt: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        OrderItemResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            productId: string;
            /** Format: uuid */
            variantId?: string | null;
            sku?: string | null;
            title: string;
            unit: components["schemas"]["ProductUnit"];
            /** Format: int32 */
            quantity: number;
            /** Format: int64 */
            priceMinor: number;
            /** Format: int64 */
            modifiersTotalMinor: number;
            /** Format: int64 */
            totalMinor: number;
            modifiers: components["schemas"]["OrderItemModifierResponse"][];
        };
        OrderItemModifierResponse: {
            /** Format: uuid */
            modifierGroupId: string;
            /** Format: uuid */
            modifierOptionId: string;
            groupCode: string;
            groupName: string;
            optionCode: string;
            optionName: string;
            applicationScope: components["schemas"]["ModifierApplicationScope"];
            /** Format: int64 */
            priceMinor: number;
            /** Format: int32 */
            quantity: number;
        };
        OrderPaymentResponse: {
            code: components["schemas"]["PaymentMethodCode"];
            name: string;
        };
        OrderDeliveryResponse: {
            method: components["schemas"]["DeliveryMethodType"];
            methodName: string;
            /** Format: int64 */
            priceMinor: number;
            currency: string;
            zoneCode?: string | null;
            zoneName?: string | null;
            /** Format: int32 */
            estimatedDays?: number | null;
            /** Format: int32 */
            estimatesMinutes?: number | null;
            /** Format: uuid */
            pickupPointId?: string | null;
            pickupPointExternalId?: string | null;
            pickupPointName?: string | null;
            pickupPointAddress?: string | null;
            address?: components["schemas"]["DeliveryAddressResponse"] | null;
        };
        DeliveryAddressRequest: {
            country?: string | null;
            region?: string | null;
            city?: string | null;
            street?: string | null;
            house?: string | null;
            apartment?: string | null;
            postalCode?: string | null;
            entrance?: string | null;
            floor?: string | null;
            intercom?: string | null;
            comment?: string | null;
            /** Format: double */
            latitude?: number | null;
            /** Format: double */
            longitude?: number | null;
        };
        DeliveryAddressResponse: {
            country?: string | null;
            region?: string | null;
            city?: string | null;
            street?: string | null;
            house?: string | null;
            apartment?: string | null;
            postalCode?: string | null;
            entrance?: string | null;
            floor?: string | null;
            intercom?: string | null;
            comment?: string | null;
            /** Format: double */
            latitude?: number | null;
            /** Format: double */
            longitude?: number | null;
        };
        /** @enum {string} */
        ModifierPriceType: "FIXED" | "FREE";
        /** @enum {string} */
        ModifierApplicationScope: "PER_ITEM" | "PER_LINE";
        CreateUploadSessionRequest: {
            targetType: components["schemas"]["MediaTargetType"];
            /** Format: uuid */
            targetId?: string | null;
            originalFilename: string;
            /**
             * @description MIME type. Allowed values come from runtime config `media.upload.allowed-content-types`
             *     (default: `image/jpeg`, `image/png`, `image/webp`).
             */
            contentType: string;
            /** Format: int64 */
            fileSize: number;
        };
        CreateUploadSessionResponse: {
            /** Format: uuid */
            id: string;
            targetType: components["schemas"]["MediaTargetType"];
            /** Format: uuid */
            targetId?: string | null;
            bucket: string;
            objectKey: string;
            originalFilename: string;
            contentType: string;
            /** Format: int64 */
            fileSize: number;
            status: components["schemas"]["MediaImageStatus"];
            uploadUrl: string;
            /** @description Current implementation returns `PUT`. */
            uploadMethod: string;
            requiredHeaders: {
                [key: string]: string;
            };
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        MediaImageResponse: {
            /** Format: uuid */
            id: string;
            targetType: components["schemas"]["MediaTargetType"];
            /** Format: uuid */
            targetId?: string | null;
            bucket: string;
            objectKey: string;
            originalFilename: string;
            contentType: string;
            /** Format: int64 */
            fileSize: number;
            status: components["schemas"]["MediaImageStatus"];
            publicUrl?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        SendTelegramTestMessageRequest: {
            message: string;
            chatIds?: string[] | null;
        };
        SendTelegramTestMessageResponse: {
            /** Format: int32 */
            attemptedRecipients: number;
            /** Format: int32 */
            sentRecipients: number;
            /** Format: int32 */
            failedRecipients: number;
            skipped: boolean;
            skipReason?: string | null;
        };
        /** @enum {string} */
        CatalogImportType: "CATEGORY" | "PRODUCT" | "MODIFIER_GROUP" | "MODIFIER_OPTION" | "PRODUCT_MODIFIER_GROUP_LINK";
        /** @enum {string} */
        CatalogImportMode: "VALIDATE_ONLY" | "CREATE_ONLY" | "UPSERT";
        /** @enum {string} */
        CatalogImportErrorCode: "MISSING_REQUIRED_FIELD" | "INVALID_BOOLEAN" | "INVALID_NUMBER" | "INVALID_ENUM" | "DUPLICATE_KEY_IN_FILE" | "CATEGORY_NOT_FOUND" | "PARENT_CATEGORY_NOT_FOUND" | "MODIFIER_GROUP_NOT_FOUND" | "PRODUCT_NOT_FOUND" | "ENTITY_ALREADY_EXISTS" | "INVALID_MIN_MAX_RULE" | "AMBIGUOUS_MATCH" | "INVALID_RELATION" | "PERSISTENCE_ERROR";
        /** @enum {string} */
        ProductUnit: "PIECE" | "KILOGRAM" | "GRAM" | "LITER" | "MILLILITER";
        /** @enum {string} */
        DeliveryMethodType: "PICKUP" | "COURIER" | "YANDEX_PICKUP_POINT";
        /** @enum {string} */
        DeliveryZoneType: "CITY" | "POSTAL_CODE" | "POLYGON";
        /** @enum {string} */
        GeoJsonGeometryType: "Polygon" | "MultiPolygon";
        /** @enum {string} */
        PaymentMethodCode: "CASH" | "CARD_ON_DELIVERY" | "CARD_ONLINE" | "SBP";
        /** @enum {string} */
        OrderCustomerType: "USER" | "GUEST";
        /** @enum {string} */
        UserRole: "CUSTOMER" | "WHOLESALE" | "MANAGER" | "ADMIN";
        /** @enum {string} */
        OrderStateType: "CREATED" | "AWAITING_CONFIRMATION" | "CONFIRMED" | "PREPARING" | "READY_FOR_PICKUP" | "OUT_FOR_DELIVERY" | "COMPLETED" | "CANCELED" | "ON_HOLD";
        /** @enum {string} */
        OrderStatusChangeSourceType: "SYSTEM" | "ADMIN" | "CUSTOMER";
        /** @enum {string} */
        MediaTargetType: "PRODUCT" | "CATEGORY" | "VARIANT";
        /** @enum {string} */
        MediaImageStatus: "PENDING" | "READY" | "DELETED";
    };
    responses: {
        /** @description Request validation failed or business rule violation */
        BadRequestError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Authentication required or invalid token/header */
        UnauthorizedError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Authenticated but not allowed */
        ForbiddenError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Resource not found */
        NotFoundError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Request conflicts with current resource state */
        ConflictError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Internal server error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        ProductIdPathParam: string;
        OrderIdPathParam: string;
        UploadIdPathParam: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    loginAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminLoginRequest"];
            };
        };
        responses: {
            /** @description Admin session tokens issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminAuthTokensResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    refreshAdminSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminRefreshTokenRequest"];
            };
        };
        responses: {
            /** @description New admin session tokens issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminAuthTokensResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    logoutAdminSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AdminLogoutRequest"];
            };
        };
        responses: {
            /** @description Session revoked or no matching session */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getAdminCategories: {
        parameters: {
            query: {
                /** @description Returns only categories with the provided activity status. */
                isActive: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Filtered category list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"][];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    upsertCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertCategoryRequest"];
            };
        };
        responses: {
            /** @description Saved category */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getAdminProducts: {
        parameters: {
            query: {
                /** @description Returns only products with the provided activity status. */
                isActive: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Filtered product list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResponse"][];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    upsertProduct: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertProductRequest"];
            };
        };
        responses: {
            /** @description Saved product */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getAdminModifierGroups: {
        parameters: {
            query?: {
                /** @description When provided, filters modifier groups by activity flag. */
                isActive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Modifier groups */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModifierGroupResponse"][];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    upsertModifierGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertModifierGroupRequest"];
            };
        };
        responses: {
            /** @description Saved modifier group */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModifierGroupResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getAdminProductById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductIdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminProductDetailsResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    importCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["CatalogImportMultipartRequest"];
            };
        };
        responses: {
            /** @description Import report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogImportResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listCatalogImportExamples: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Available example files */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogImportExampleResponse"][];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    downloadCatalogImportExample: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                importType: components["schemas"]["CatalogImportType"];
                importMode: components["schemas"]["CatalogImportMode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSV file content */
            200: {
                headers: {
                    /** @description Suggested attachment filename. */
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    importCatalogLegacy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    importType: components["schemas"]["CatalogImportType"];
                    importMode: components["schemas"]["CatalogImportMode"];
                };
            };
        };
        responses: {
            /** @description Import report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogImportResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listCatalogImportExamplesLegacy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Available example files */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogImportExampleResponse"][];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    downloadCatalogImportExampleLegacy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                importType: components["schemas"]["CatalogImportType"];
                importMode: components["schemas"]["CatalogImportMode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSV file content */
            200: {
                headers: {
                    /** @description Suggested attachment filename. */
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getAdminDeliveryMethodSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Delivery method settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryMethodSettingResponse"][];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    upsertAdminDeliveryMethodSetting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertDeliveryMethodSettingRequest"];
            };
        };
        responses: {
            /** @description Saved delivery method setting */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryMethodSettingResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getAdminDeliveryZones: {
        parameters: {
            query?: {
                /** @description When provided, filters delivery zones by activity flag. */
                isActive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Delivery zones */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryZoneResponse"][];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    upsertAdminDeliveryZone: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertDeliveryZoneRequest"];
            };
        };
        responses: {
            /** @description Saved delivery zone */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryZoneResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getAdminDeliveryZone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                zoneId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Delivery zone */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryZoneResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateAdminDeliveryZone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                zoneId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertDeliveryZoneRequest"];
            };
        };
        responses: {
            /** @description Updated delivery zone */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryZoneResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteAdminDeliveryZone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                zoneId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Delivery zone deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getAdminDeliveryTariffs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Delivery tariffs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryTariffResponse"][];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    upsertAdminDeliveryTariff: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertDeliveryTariffRequest"];
            };
        };
        responses: {
            /** @description Saved delivery tariff */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryTariffResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteAdminDeliveryTariff: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tariffId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Delivery tariff deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getAdminPickupPoints: {
        parameters: {
            query?: {
                /** @description When provided, filters pickup points by activity flag. */
                isActive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pickup points */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPickupPointResponse"][];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    upsertAdminPickupPoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertPickupPointRequest"];
            };
        };
        responses: {
            /** @description Saved pickup point */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPickupPointResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    detectAdminPickupPointAddress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DetectPickupPointAddressRequest"];
            };
        };
        responses: {
            /** @description Detected pickup point address or `null` when geocoder returned no result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetectPickupPointAddressResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteAdminPickupPoint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pickupPointId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pickup point deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getAdminCheckoutPaymentRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Checkout payment rules */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutPaymentRuleResponse"][];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    replaceAdminCheckoutPaymentRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceCheckoutPaymentRulesRequest"];
            };
        };
        responses: {
            /** @description Updated checkout payment rules */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutPaymentRuleResponse"][];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getOrderStatuses: {
        parameters: {
            query?: {
                includeInactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order status definitions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderStatusResponse"][];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createOrderStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertOrderStatusRequest"];
            };
        };
        responses: {
            /** @description Created order status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderStatusResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            409: components["responses"]["ConflictError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getOrderStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                statusId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order status definition */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderStatusResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateOrderStatusDefinition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                statusId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertOrderStatusRequest"];
            };
        };
        responses: {
            /** @description Updated order status definition */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderStatusResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            409: components["responses"]["ConflictError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deactivateOrderStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                statusId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deactivated order status definition */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderStatusResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            409: components["responses"]["ConflictError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getOrderStatusTransitions: {
        parameters: {
            query?: {
                statusId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order status transitions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderStatusTransitionResponse"][];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createOrderStatusTransition: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderStatusTransitionRequest"];
            };
        };
        responses: {
            /** @description Created order status transition */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderStatusTransitionResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            409: components["responses"]["ConflictError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteOrderStatusTransition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transitionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transition deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getAdminOrders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Orders in admin queue */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"][];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getAdminOrderByNumber: {
        parameters: {
            query: {
                /** @description Order number from `OrderResponse.orderNumber`. */
                orderNumber: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order found by number */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getAvailableOrderStatusTransitions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: components["parameters"]["OrderIdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Available transitions for order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderStatusTransitionResponse"][];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getOrderStatusHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: components["parameters"]["OrderIdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order status history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderStatusHistoryResponse"][];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    changeOrderStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: components["parameters"]["OrderIdPathParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrderStatusRequest"];
            };
        };
        responses: {
            /** @description Updated order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            409: components["responses"]["ConflictError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateOrderStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: components["parameters"]["OrderIdPathParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrderStatusRequest"];
            };
        };
        responses: {
            /** @description Updated order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            409: components["responses"]["ConflictError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    sendTelegramTestMessage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendTelegramTestMessageRequest"];
            };
        };
        responses: {
            /** @description Test message delivery report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendTelegramTestMessageResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createMediaUploadSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUploadSessionRequest"];
            };
        };
        responses: {
            /** @description Upload session created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateUploadSessionResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    completeMediaUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uploadId: components["parameters"]["UploadIdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Media image metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaImageResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
