/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/methods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available authentication methods */
        get: operations["getAvailableAuthMethods"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/phone/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start phone authentication challenge */
        post: operations["startPhoneAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/phone/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm phone auth challenge with code */
        post: operations["confirmPhoneAuthCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/email/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start email authentication challenge */
        post: operations["startEmailAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/email/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm email auth challenge with code */
        post: operations["confirmEmailAuthCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/telegram/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Telegram authentication */
        post: operations["completeTelegramAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/max/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete MAX authentication */
        post: operations["completeMaxAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh access and refresh tokens */
        post: operations["refreshAuthSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke one refresh session for current user */
        post: operations["logoutCurrentSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke all sessions for current user */
        post: operations["logoutAllSessions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login as admin */
        post: operations["loginAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh admin access and refresh tokens */
        post: operations["refreshAdminSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke one admin refresh session */
        post: operations["logoutAdminSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get or create active cart for current actor */
        get: operations["getCart"];
        put?: never;
        post?: never;
        /** Remove all items from active cart */
        delete: operations["clearCart"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cart/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add product to active cart */
        post: operations["addCartItem"];
        delete?: never;
        options?: never;
        head?: never;
        /** Change quantity of a cart item */
        patch: operations["changeCartItemQuantity"];
        trace?: never;
    };
    "/api/v1/cart/items/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove product from active cart */
        delete: operations["removeCartItem"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List catalog categories
         * @description Returns categories sorted by name ascending.
         */
        get: operations["getCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List catalog products
         * @description Returns active products sorted by `createdAt` descending.
         *     Supports filters by `categoryId` and case-insensitive title `query`.
         */
        get: operations["getProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/products/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one active product by id */
        get: operations["getProductById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/catalog/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create or update category */
        post: operations["upsertCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/catalog/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create or update product */
        post: operations["upsertProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Checkout current actor cart */
        post: operations["checkout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/guest/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create guest order from provided items */
        post: operations["guestCheckout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one order visible to current actor */
        get: operations["getOrderById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List orders of current actor
         * @description Returns orders sorted by `createdAt` descending.
         */
        get: operations["getMyOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/orders/{orderId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update order status */
        patch: operations["updateOrderStatus"];
        trace?: never;
    };
    "/api/v1/admin/media/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create direct upload session for media image
         * @description Returns pre-signed upload URL and required headers.
         *     Actual binary upload happens directly to object storage URL, not via this backend.
         */
        post: operations["createMediaUploadSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/media/uploads/{uploadId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete upload session and bind image to target entity */
        post: operations["completeMediaUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiError: {
            /** @enum {string} */
            code: "VALIDATION_ERROR" | "UNAUTHORIZED" | "FORBIDDEN" | "NOT_FOUND" | "INTERNAL_ERROR";
            message: string;
            /** @description Request trace id (`X-Trace-Id`) when available. */
            traceId?: string | null;
            details?: {
                [key: string]: unknown;
            } | null;
        };
        AvailableAuthMethodsResponse: {
            methods: components["schemas"]["AuthMethod"][];
        };
        AuthChallengeResponse: {
            /** Format: uuid */
            challengeId: string;
            method: components["schemas"]["AuthMethod"];
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            resendAvailableAt?: string | null;
            /** @description Current implementation returns `CONFIRM_CODE`. */
            nextStep: string;
        };
        AuthTokensResponse: {
            accessToken: string;
            /** Format: date-time */
            accessTokenExpiresAt: string;
            refreshToken: string;
            /** Format: date-time */
            refreshTokenExpiresAt: string;
            isNewUser: boolean;
            /** Format: uuid */
            userId: string;
        };
        AdminLoginRequest: {
            login: string;
            password: string;
            deviceId?: string | null;
        };
        AdminRefreshTokenRequest: {
            refreshToken: string;
            deviceId?: string | null;
        };
        AdminLogoutRequest: {
            refreshToken?: string | null;
        };
        AdminAuthTokensResponse: {
            accessToken: string;
            /** Format: date-time */
            accessTokenExpiresAt: string;
            refreshToken: string;
            /** Format: date-time */
            refreshTokenExpiresAt: string;
            /** Format: uuid */
            adminId: string;
        };
        StartPhoneAuthRequest: {
            phone: string;
            method: components["schemas"]["AuthMethodStartPhone"];
        };
        ConfirmPhoneCodeRequest: {
            /** Format: uuid */
            challengeId: string;
            code: string;
            deviceId?: string | null;
        };
        StartEmailAuthRequest: {
            /** Format: email */
            email: string;
        };
        ConfirmEmailCodeRequest: {
            /** Format: uuid */
            challengeId: string;
            code: string;
            deviceId?: string | null;
        };
        TelegramCompleteAuthRequest: {
            authPayload: string;
            deviceId?: string | null;
        };
        MaxCompleteAuthRequest: {
            authPayload: string;
            deviceId?: string | null;
        };
        RefreshTokenRequest: {
            refreshToken: string;
            deviceId?: string | null;
        };
        LogoutRequest: {
            refreshToken?: string | null;
        };
        AddCartItemRequest: {
            /** Format: uuid */
            productId: string;
            /** Format: int32 */
            quantity: number;
        };
        ChangeCartItemQuantityRequest: {
            /** Format: uuid */
            productId: string;
            /** Format: int32 */
            quantity: number;
        };
        CartResponse: {
            /** Format: uuid */
            id: string;
            status: components["schemas"]["CartStatus"];
            items: components["schemas"]["CartItemResponse"][];
            /** Format: int64 */
            totalPriceMinor: number;
        };
        CartItemResponse: {
            /** Format: uuid */
            productId: string;
            title: string;
            unit: components["schemas"]["ProductUnit"];
            /** Format: int32 */
            countStep: number;
            /** Format: int32 */
            quantity: number;
            /** Format: int64 */
            priceMinor: number;
            /** Format: int64 */
            lineTotalMinor: number;
        };
        CategoryResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            imageUrl?: string | null;
        };
        ProductResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            categoryId: string;
            title: string;
            slug: string;
            description?: string | null;
            /** Format: int64 */
            priceMinor: number;
            /** Format: int64 */
            oldPriceMinor?: number | null;
            sku?: string | null;
            imageUrl?: string | null;
            unit: components["schemas"]["ProductUnit"];
            /** Format: int32 */
            countStep: number;
        };
        UpsertCategoryRequest: {
            /** Format: uuid */
            id?: string | null;
            name: string;
            slug?: string | null;
            imageUrl?: string | null;
            /** @default true */
            isActive: boolean;
        };
        UpsertProductRequest: {
            /** Format: uuid */
            id?: string | null;
            /** Format: uuid */
            categoryId: string;
            title: string;
            slug?: string | null;
            description?: string | null;
            /** Format: int64 */
            priceMinor: number;
            /** Format: int64 */
            oldPriceMinor?: number | null;
            sku?: string | null;
            imageUrl?: string | null;
            unit: components["schemas"]["ProductUnit"];
            /** Format: int32 */
            countStep: number;
            /** @default true */
            isActive: boolean;
        };
        CheckoutRequest: {
            customerName?: string | null;
            customerPhone?: string | null;
            customerEmail?: string | null;
            deliveryType: components["schemas"]["OrderDeliveryType"];
            deliveryAddress?: string | null;
            comment?: string | null;
        };
        GuestCheckoutRequest: {
            items: components["schemas"]["GuestCheckoutItemRequest"][];
            customerName: string;
            customerPhone: string;
            customerEmail?: string | null;
            deliveryType: components["schemas"]["OrderDeliveryType"];
            deliveryAddress?: string | null;
            comment?: string | null;
        };
        GuestCheckoutItemRequest: {
            /** Format: uuid */
            productId: string;
            /** Format: int32 */
            quantity: number;
        };
        UpdateOrderStatusRequest: {
            status: components["schemas"]["OrderStatus"];
        };
        OrderResponse: {
            /** Format: uuid */
            id: string;
            orderNumber: string;
            customerType: components["schemas"]["OrderCustomerType"];
            /** Format: uuid */
            userId?: string | null;
            guestInstallId?: string | null;
            customerName?: string | null;
            customerPhone?: string | null;
            customerEmail?: string | null;
            status: components["schemas"]["OrderStatus"];
            deliveryType: components["schemas"]["OrderDeliveryType"];
            deliveryAddress?: string | null;
            comment?: string | null;
            items: components["schemas"]["OrderItemResponse"][];
            /** Format: int64 */
            subtotalMinor: number;
            /** Format: int64 */
            deliveryFeeMinor: number;
            /** Format: int64 */
            totalMinor: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        OrderItemResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            productId: string;
            title: string;
            unit: components["schemas"]["ProductUnit"];
            /** Format: int32 */
            quantity: number;
            /** Format: int64 */
            priceMinor: number;
            /** Format: int64 */
            totalMinor: number;
        };
        CreateUploadSessionRequest: {
            targetType: components["schemas"]["MediaTargetType"];
            /** Format: uuid */
            targetId: string;
            originalFilename: string;
            /**
             * @description MIME type. Allowed values come from runtime config `media.upload.allowed-content-types`
             *     (default: `image/jpeg`, `image/png`, `image/webp`).
             */
            contentType: string;
            /** Format: int64 */
            fileSize: number;
        };
        CreateUploadSessionResponse: {
            /** Format: uuid */
            id: string;
            targetType: components["schemas"]["MediaTargetType"];
            /** Format: uuid */
            targetId: string;
            bucket: string;
            objectKey: string;
            originalFilename: string;
            contentType: string;
            /** Format: int64 */
            fileSize: number;
            status: components["schemas"]["MediaImageStatus"];
            uploadUrl: string;
            /** @description Current implementation returns `PUT`. */
            uploadMethod: string;
            requiredHeaders: {
                [key: string]: string;
            };
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        MediaImageResponse: {
            /** Format: uuid */
            id: string;
            targetType: components["schemas"]["MediaTargetType"];
            /** Format: uuid */
            targetId: string;
            bucket: string;
            objectKey: string;
            originalFilename: string;
            contentType: string;
            /** Format: int64 */
            fileSize: number;
            status: components["schemas"]["MediaImageStatus"];
            publicUrl?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @enum {string} */
        AuthMethod: "PHONE_SMS" | "PHONE_CALL" | "TELEGRAM" | "MAX" | "EMAIL";
        /** @enum {string} */
        AuthMethodStartPhone: "PHONE_SMS" | "PHONE_CALL";
        /** @enum {string} */
        ProductUnit: "PIECE" | "KILOGRAM" | "GRAM" | "LITER" | "MILLILITER";
        /** @enum {string} */
        CartStatus: "ACTIVE" | "ORDERED" | "MERGED" | "ABANDONED";
        /** @enum {string} */
        OrderCustomerType: "USER" | "GUEST";
        /** @enum {string} */
        OrderDeliveryType: "PICKUP" | "DELIVERY";
        /** @enum {string} */
        OrderStatus: "PENDING" | "CONFIRMED" | "CANCELLED" | "COMPLETED";
        /** @enum {string} */
        MediaTargetType: "PRODUCT" | "CATEGORY";
        /** @enum {string} */
        MediaImageStatus: "PENDING" | "READY";
    };
    responses: {
        /** @description Request validation failed or business rule violation */
        BadRequestError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Authentication required or invalid token/header */
        UnauthorizedError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Authenticated but not allowed */
        ForbiddenError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Resource not found */
        NotFoundError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Internal server error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        ProductIdPathParam: string;
        OrderIdPathParam: string;
        UploadIdPathParam: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAvailableAuthMethods: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Available authentication methods */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailableAuthMethodsResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    startPhoneAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartPhoneAuthRequest"];
            };
        };
        responses: {
            /** @description Phone auth challenge created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthChallengeResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    confirmPhoneAuthCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmPhoneCodeRequest"];
            };
        };
        responses: {
            /** @description Session tokens issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokensResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    startEmailAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartEmailAuthRequest"];
            };
        };
        responses: {
            /** @description Email auth challenge created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthChallengeResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    confirmEmailAuthCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmEmailCodeRequest"];
            };
        };
        responses: {
            /** @description Session tokens issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokensResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    completeTelegramAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelegramCompleteAuthRequest"];
            };
        };
        responses: {
            /** @description Session tokens issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokensResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    completeMaxAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaxCompleteAuthRequest"];
            };
        };
        responses: {
            /** @description Session tokens issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokensResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    refreshAuthSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description New session tokens issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokensResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    logoutCurrentSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Session revoked or no matching session */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    logoutAllSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All user sessions revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    loginAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminLoginRequest"];
            };
        };
        responses: {
            /** @description Admin session tokens issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminAuthTokensResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    refreshAdminSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminRefreshTokenRequest"];
            };
        };
        responses: {
            /** @description New admin session tokens issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminAuthTokensResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    logoutAdminSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AdminLogoutRequest"];
            };
        };
        responses: {
            /** @description Session revoked or no matching session */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getCart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active cart */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    clearCart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cleared cart */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    addCartItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddCartItemRequest"];
            };
        };
        responses: {
            /** @description Updated cart */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    changeCartItemQuantity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeCartItemQuantityRequest"];
            };
        };
        responses: {
            /** @description Updated cart */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    removeCartItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductIdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated cart */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getCategories: {
        parameters: {
            query?: {
                /** @description When true (default), returns only active categories. */
                activeOnly?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Category list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"][];
                };
            };
            400: components["responses"]["BadRequestError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getProducts: {
        parameters: {
            query?: {
                categoryId?: string;
                query?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResponse"][];
                };
            };
            400: components["responses"]["BadRequestError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getProductById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductIdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    upsertCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertCategoryRequest"];
            };
        };
        responses: {
            /** @description Saved category */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    upsertProduct: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertProductRequest"];
            };
        };
        responses: {
            /** @description Saved product */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    checkout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutRequest"];
            };
        };
        responses: {
            /** @description Created order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    guestCheckout: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional guest installation id saved into order (`guestInstallId`). */
                "X-Install-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GuestCheckoutRequest"];
            };
        };
        responses: {
            /** @description Created guest order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getOrderById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: components["parameters"]["OrderIdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getMyOrders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Actor orders */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"][];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateOrderStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: components["parameters"]["OrderIdPathParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrderStatusRequest"];
            };
        };
        responses: {
            /** @description Updated order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createMediaUploadSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUploadSessionRequest"];
            };
        };
        responses: {
            /** @description Upload session created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateUploadSessionResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    completeMediaUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uploadId: components["parameters"]["UploadIdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Media image metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaImageResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
